[options]
library = "SpeechProvider"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
  "SpeechProvider.StreamWriter",
  "SpeechProvider.EventType",
  "SpeechProvider.VoiceFeature"
]

manual = []
