[package]
name = "speechprovider"
version = "0.1.0"
edition = "2021"

[dependencies]
glib = { version = "0.20.7" }
speechprovider-sys = { path = "./sys" }

[dependencies.gobject]
package = "gobject-sys"
git = "https://github.com/gtk-rs/gtk-rs-core"

